shoppr_site/shoppr_app/auth_api/urls.py
from django.urls import path
from . import views

from rest_framework_simplejwt.views import (
    TokenRefreshView,
)

urlpatterns = [
    path('', views.getRoutes),
    path('token/', views.MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

shoppr_site/shoppr_app/urls.py
from django.urls import path

from . import views

app_name = "shoppr_app" 

urlpatterns = [
    path('', views.index, name='index'),
    path('shop', views.shop, name='shop'),
    path('search/<str:search_word>', views.search_json, name='search'),
    path('base', views.base, name='base'),
    path('register', views.register, name='register'),
    path('login', views.login_request, name='login'),
    path('logout', views.logout_request, name='logout'),
    path('wishlists/<int:user_id>', views.getUserWishlist, name = 'user_wishlist'),
    path('wishlist/', views.addAWishlist, name =  'newWishlist'),
]

shoppr_site/shoppr_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shoppr/', include('shoppr_app.urls')),
    path('accounts/', include('allauth.urls')),
     path('auth_api/', include('shoppr_app.auth_api.urls'))
]

shoppr_site/shoppr_app/models.py
from tkinter import CASCADE
from django.db import models
from django.contrib.auth.models import User

class Product(models.Model):
    product_id = models.IntegerField()
    store = models.TextField()
    name = models.TextField()
    image_url = models.URLField()
    url = models.URLField()
    standard_price = models.DecimalField(decimal_places = 2, max_digits = 5)
    sales_price = models.DecimalField(decimal_places = 2, max_digits = 5)
    unit_discount = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"({self.product_id}) {self.name} - {self.store}"


class WishListItem(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    product = models.ForeignKey(Product, on_delete = models.CASCADE)


    def __str__(self):
        return f"User: {self.user} - Product: {self.product}"

shoppr_site/shoppr_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

shoppr_site/shoppr_app/auth_api/views.py
from django.http import JsonResponse
from rest_framework import permissions
from rest_framework.response import Response
from rest_framework.decorators import api_view, permission_classes
from rest_framework.permissions import IsAuthenticated

from rest_framework_simplejwt.serializers import TokenObtainPairSerializer
from rest_framework_simplejwt.views import TokenObtainPairView

class MyTokenObtainPairSerializer(TokenObtainPairSerializer):
    @classmethod
    def get_token(cls, user):
        token = super().get_token(user)

        # Add custom claims
        token['username'] = user.username
        # ...

        return token


class MyTokenObtainPairView(TokenObtainPairView):
    serializer_class = MyTokenObtainPairSerializer


@api_view(['GET'])
def getRoutes(request):
    routes = [
        '/auth_api/token',
        '/auth_api/token/refresh',
    ]

    return Response(routes)

shoppr_site/shoppr_app/views.py
from curses.ascii import US
import re
from django.shortcuts import  render, redirect

from django.core import serializers
from .forms import NewUserForm
from django.contrib import messages
from .models import Product, WishListItem
from .serializers import ProductSerializer, WishlistItemSerializer
from django.contrib.auth.models import User

from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm 

from rest_framework.renderers import JSONRenderer
from rest_framework import permissions, status
from rest_framework.response import Response
from rest_framework.decorators import api_view, permission_classes

from django.http import HttpResponse, JsonResponse
from scrapyd_api import ScrapydAPI
import json
from time import sleep
import os
from django.shortcuts import render

SHEIN_FILE_PATH = "shoppr_app/shein_items.json"
ASOS_FILE_PATH = "shoppr_app/asos_items.json"


def logout_request(request):
	logout(request)
	messages.info(request, "You have successfully logged out.") 
	return redirect("shoppr_app:index")

@api_view(['POST'])
def login_request(request):
	if request.method == "POST":
		data1 = {
					"username": "user_one", 
					"password": "testuser101$"
				}
		print(request)
		form = AuthenticationForm(request, data=request.data)
		print(request.data)
		if form.is_valid():
			print("got here 1")
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user, backend="django.contrib.auth.backends.ModelBackend")
				print(f"User name is {user.get_username()}")
				print(f"User ID is {user.password}")
				user = {
					'id': user.pk,
					'username': user.get_username(),
					'password': user.password
				}
				response = {'status': 'OK', 'user': user}
				# messages.info(request, f"You are now logged in as {username}.")
				# return redirect("shoppr_app:index")
				# return Response(response)
				return Response(response, status = status.HTTP_200_OK)
			else:
				print("got here 2")
				response = {'status': 'ERROR'}
				# return Response(response)
				return Response(response, status = status.HTTP_200_OK)
		else:
			print("got here 3")
			response = {'status': 'ERROR'}
			# return Response(response)
			return Response(response, status = status.HTTP_400_BAD_REQUEST)
	print("got here 4")
	response = {'status': 'ERROR'}
	# return Response(response)
	return Response(response)
	# form = AuthenticationForm()
	# return render(request, "shoppr_app/login.html", context={"login_form":form})

@api_view(['POST'])
def addAWishlist(request):
	if request.method == "POST":
		new_wishlist_data = request.data
		product = Product(
						product_id = new_wishlist_data.product_id,
						store=new_wishlist_data.product_brand, 
						name=new_wishlist_data.product_name, 
						image_url =new_wishlist_data.product_img_url, 
						url = new_wishlist_data.product_url, 
						standard_price = new_wishlist_data.product_std_price, 
						sales_price = new_wishlist_data.product_sales_price, 
						unit_discount = new_wishlist_data.product_unit_discount)
		try:
			product.save()
			print("Product saved")
		except:
			print("Error saving the product")
		user = User.objects.get(id = new_wishlist_data.user_id)
	
		wishlist = WishListItem(user = user, product = product)
		try:
			wishlist.save()
			print("Wishlist saved")
		except:
			print("Error saving wishlist item")
	else:
		print("Invalid request method")

# @api_view(['GET'])
def getUserWishlist(request, user_id):
	# user_id = int(request.GET.get('user_id'))
	print('entered')
	print(f"User ID : {user_id}")
	req_user = User.objects.get(id = user_id)
	print("here")

	user_wishlist_obj = WishListItem.objects.filter(user = req_user)
	print(user_wishlist_obj)

	user_wishlist_str = serializers.serialize('json', user_wishlist_obj)
	print(user_wishlist_str)
	
	user_wishlist = json.loads(user_wishlist_str)
	wishlist_products = [Product.objects.get(id = wishlist['fields']['product']) for wishlist in user_wishlist]
	wishlist_products_json = json.loads(serializers.serialize('json', wishlist_products))

	# return HttpResponse(user_wishlist_str, content_type='application/json')
	
	return  JsonResponse(wishlist_products_json, safe=False)

	# user_wish_serialized = WishlistItemSerializer(user_wishlist)
	# print(user_wish_serialized)
	# response = JSONRenderer().render(user_wish_serialized.data)
	# return response
  

@api_view(['POST'])
def register(request):
	if request.method == "POST":
		print(request.data)
		form = NewUserForm(request.data)
		print(form)
		if form.is_valid():
			user = form.save()
			response = {
				'status': 'OK',
			}
			# messages.success(request, "Registration successful." )
			# login(request, user, backend="django.contrib.auth.backends.ModelBackend")
			# return redirect("shoppr_app:index")
			print(response)
			return Response(response, status = status.HTTP_200_OK)
		else:
			response = {
				'status': 'ERROR',
			}
			# messages.error(request, "Unsuccessful registration. Invalid information.")
			print(response)
			return Response(response, status.HTTP_400_BAD_REQUEST)
	# form = NewUserForm()
	# return render (request, "shoppr_app/register.html", context={"register_form":form})


def clean_data_files():
	if os.path.exists(SHEIN_FILE_PATH):
		os.remove(SHEIN_FILE_PATH)

	# if os.path.exists('shoppr_app/boohoo_items.json'):
	# 	os.remove('shoppr_app/boohoo_items.json')

	if os.path.exists(ASOS_FILE_PATH):
		os.remove(ASOS_FILE_PATH)


def search(search_word):
	clean_data_files()
	scrapyd = ScrapydAPI('http://localhost:6800')
	scrapyd.schedule('shoppr_scraper', 'shein', search_word=search_word)
	scrapyd.schedule('shoppr_scraper', 'asos', search_word=search_word)
	sleep(50)
	with open(SHEIN_FILE_PATH, encoding='utf-8', errors='ignore') as shein_file:
		products_data = json.load(shein_file, strict=False)
		
	with open(ASOS_FILE_PATH, encoding='utf-8', errors='ignore') as asos_file:
		products_data.extend(json.load(asos_file, strict=False))

	# with open(SHEIN_FILE_PATH, 'r') as shein_file:
	# 	if shein_file.read():
	# 		products_data = json.loads(shein_file.read())
	# with open(ASOS_FILE_PATH, 'r') as asos_file:
	# 	if asos_file.read():
	# 		products_data.extend(json.loads(asos_file.read()))

	# shein_file  = open('shoppr_app/shein_items.json')
	# asos_file =  open('shoppr_app/asos_items.json')
	# products_data = json.load(shein_file)
	# products_data.extend(json.load(asos_file))
	products_data.sort(key = lambda product: float(product['product_sales_price']))
	data = {'search_word': search_word, 'number_of_results': len(products_data), 'results': products_data}
	return data  

def search_json(request, search_word):
	data = search(search_word)
	return  JsonResponse(data, safe=False)

def base(request):
	return render(request, 'shoppr_app/base.html', {})

def index(request):
	return render(request, 'shoppr_app/index.html', {})

def shop(request):
	search_word = request.GET.get('search_word')
	data = search(search_word)

	return render(request, 'shoppr_app/shop.html', data)

shoppr_site/shoppr_app/templates/shoppr_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Fashi Template">
    <meta name="keywords" content="Fashi, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Shoppr | Your One-Stop-Shop</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Muli:300,400,500,600,700,800,900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'shoppr_app/css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'shoppr_app/css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'shoppr_app/css/themify-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'shoppr_app/css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'shoppr_app/css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'shoppr_app/css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'shoppr_app/css/jquery-ui.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'shoppr_app/css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'shoppr_app/css/style.css' %}" type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->
    <header class="header-section">
        <div class="container">
            <div class="inner-header">
                <div class="row">
                    <div class="col-lg-2 col-md-2">
                        <div class="logo">
                            <a href="./index.html">
                                <!-- <img src="{% static 'shoppr_app/img/logo.png' %}" alt=""> -->
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-7 col-md-5">
                        <div class="advanced-search">
                            <button type="button" class="category-btn">All Categories</button>
                            <form action="#" class="input-group">
                                <input type="text" placeholder="What do you need?">
                                <button type="button"><i class="ti-search"></i></button>
                            </form>
                        </div>
                    </div>
                    <div class="col-lg-3 text-right col-md-5">
                        <ul class="nav-right">
                            <!-- <li class="heart-icon"><a href="#">
                                    <i class="icon_heart_alt"></i>
                                    <span>1</span>
                                </a>
                            </li> -->
                            {% if user.is_authenticated %}
                                <li class="cart-icon"><a href="">
                                        <i class="icon_bag_alt"></i>
                                        <!-- <span>3</span> -->
                                    </a>
                                    <div class="cart-hover">
                                        <div class="select-items">
                                            <table>
                                                <tbody>
                                                    <tr>
                                                        <td class="si-pic"><img src="{% static 'shoppr_app/img/select-product-1.jpg' %}" alt=""></td>
                                                        <td class="si-text">
                                                            <div class="product-selected">
                                                                <p>$60.00 x 1</p>
                                                                <h6>Kabino Bedside Table</h6>
                                                            </div>
                                                        </td>
                                                        <td class="si-close">
                                                            <i class="ti-close"></i>
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td class="si-pic"><img src="{% static 'shoppr_app/img/select-product-2.jpg' %}" alt=""></td>
                                                        <td class="si-text">
                                                            <div class="product-selected">
                                                                <p>$60.00 x 1</p>
                                                                <h6>Kabino Bedside Table</h6>
                                                            </div>
                                                        </td>
                                                        <td class="si-close">
                                                            <i class="ti-close"></i>
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                        <div class="select-total">
                                            <span>total:</span>
                                            <h5>$120.00</h5>
                                        </div>
                                        <div class="select-button">
                                            <a href="#" class="primary-btn view-card">VIEW CARD</a>
                                            <a href="#" class="primary-btn checkout-btn">CHECK OUT</a>
                                        </div>
                                    </div>
                                </li>
                            {% endif %}
                            <!-- <li class="cart-price">$150.00</li> -->
                            {% if user.is_authenticated %}
                                <li class="cart-price">
                                    <a href="{% url 'shoppr_app:logout' %}">
                                        <i class="fa fa-user"></i>
                                        <span>Hi, {{user.username}}!</span>
                                    </a>
                                </li>
                            {% else %}
                                <li class="cart-price">
                                    <a href="{% url 'shoppr_app:register' %}">
                                        <i class="fa fa-user"></i>
                                        <span>Sign In</span>
                                    </a>
                                </li>
                            {% endif %}
                             <!-- {% if user.is_authenticated %}
                                <li class="cart-price">
                                        <span>Hi, {{user.username}}!</span>
                                    </a>
                                </li>
                            {% endif %} -->
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Header End -->
    {% block content %}
    <!-- Body of the page -->
    {% endblock %}

    <!-- Partner Logo Section Begin -->
    <div class="partner-logo">
        <div class="container">
            <div class="logo-carousel owl-carousel">
                <div class="logo-item">
                    <div class="tablecell-inner">
                        <img src="{% static 'shoppr_app/img/logo-carousel/logo-1.png' %}" alt="">
                    </div>
                </div>
                <div class="logo-item">
                    <div class="tablecell-inner">
                        <img src="{% static 'shoppr_app/img/logo-carousel/logo-2.png' %}" alt="">
                    </div>
                </div>
                <div class="logo-item">
                    <div class="tablecell-inner">
                        <img src="{% static 'shoppr_app/img/logo-carousel/logo-3.png' %}" alt="">
                    </div>
                </div>
                <div class="logo-item">
                    <div class="tablecell-inner">
                        <img src="{% static 'shoppr_app/img/logo-carousel/logo-4.png' %}" alt="">
                    </div>
                </div>
                <div class="logo-item">
                    <div class="tablecell-inner">
                        <img src="{% static 'shoppr_app/img/logo-carousel/logo-5.png' %}" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Partner Logo Section End -->

    <!-- Footer Section Begin -->
    <footer class="footer-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="footer-left">
                        <div class="footer-logo">
                            <a href="#"><img src="{% static 'shoppr_app/img/footer-logo.png' %}" alt=""></a>
                        </div>
                        <ul>
                            <li>Address: 60-49 Road 11378 New York</li>
                            <li>Phone: +65 11.188.888</li>
                            <li>Email: hello.colorlib@gmail.com</li>
                        </ul>
                        <div class="footer-social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-pinterest"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-2 offset-lg-1">
                    <div class="footer-widget">
                        <h5>Information</h5>
                        <ul>
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">Checkout</a></li>
                            <li><a href="#">Contact</a></li>
                            <li><a href="#">Serivius</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-2">
                    <div class="footer-widget">
                        <h5>My Account</h5>
                        <ul>
                            <li><a href="#">My Account</a></li>
                            <li><a href="#">Contact</a></li>
                            <li><a href="#">Shopping Cart</a></li>
                            <li><a href="#">Shop</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="newslatter-item">
                        <h5>Join Our Newsletter Now</h5>
                        <p>Get E-mail updates about our latest shop and special offers.</p>
                        <form action="#" class="subscribe-form">
                            <input type="text" placeholder="Enter Your Mail">
                            <button type="button">Subscribe</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="copyright-reserved">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="copyright-text">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </div>
                        <div class="payment-pic">
                            <img src="{% static 'shoppr_app/img/payment-method.png' %}" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->

    <!-- Js Plugins -->
    <script src="{% static 'shoppr_app/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'shoppr_app/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'shoppr_app/js/jquery-ui.min.js' %}"></script>
    <script src="{% static 'shoppr_app/js/jquery.countdown.min.js' %}"></script>
    <script src="{% static 'shoppr_app/js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'shoppr_app/js/jquery.zoom.min.js' %}"></script>
    <script src="{% static 'shoppr_app/js/jquery.dd.min.js' %}"></script>
    <script src="{% static 'shoppr_app/js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'shoppr_app/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'shoppr_app/js/main.js' %}"></script>
</body>

</html>

shoppr_site/shoppr_app/templates/shoppr_app/login.html
{% extends 'shoppr_app/base.html' %}
{% block content %}

{% load crispy_forms_tags %}
{% load static %}

 <!-- Login Section Begin -->
    <div class="register-login-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 offset-lg-3">
                    <div class="login-form">
                        <h2>Login</h2>
                        <form action="{% url 'shoppr_app:login' %}" method="POST">
                        	{% csrf_token %}
                        	<div class="group-input" id = "div_id_username">
                                <label for="id_username" class="requiredField">Username *</label>
                                <input type="text" id="id_username" name = "username" maxlength = '150' autofocus required autocapitalize="none">
                            </div>
                            <div id="div_id_password" class="group-input"> 
                            	<label for="id_password" class="requiredField">Password *</label> 
								<input type="password" name="password" autocomplete="current-password" required id="id_password"> 
							</div>
                            <!-- <div class="group-input gi-check">
                                <div class="gi-more">
                                    <label for="save-pass">
                                        Save Password
                                        <input type="checkbox" id="save-pass">
                                        <span class="checkmark"></span>
                                    </label>
                                    <a href="#" class="forget-pass">Forget your Password</a>
                                </div>
                            </div> -->
                            <button type="submit" class="site-btn login-btn">Log In</button>
                        </form>
                        <div class="switch-login">
                            <a href="{% url 'shoppr_app:register' %}" class="or-login">Or Create An Account</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Login Form Section End -->

<!-- <div class="container py-5">
  <h1>Login</h1>
  <form method="POST">
    {% csrf_token %}
    {{ login_form|crispy }}
    <button class="btn btn-primary" type="submit">Login</button>
  </form>
  <p class="text-center">Don't have an account? <a href="{% url 'shoppr_app:register' %}">Create an account</a>.</p>
</div> -->

{% endblock %}

shoppr_site/shoppr_app/templates/shoppr_app/logout.html
{% extends 'shoppr_app/base.html' %}

{% block content %}

{% load crispy_forms_tags %}
{% load static %}

<div class="collapse navbar-collapse" id="navbarText">
	<ul class="navbar-nav mr-auto">
	  {% if user.is_authenticated %}
	  
	  <li class="nav-item">
	    <a class="nav-link" href="{% url 'shoppr_app:logout' %}">Logout</a>
	  </li>
	  <li class="nav-item">
	    <a class="nav-link" href="#">Welcome, {{user.username}}</a>
	  </li>

	  {% else %}

	  <li class="nav-item">
	    <a class="nav-link" href="{% url 'shoppr_app:login' %}">Login</a>
	  </li>

	  {% endif %}
	</ul>
</div>

{% endblock %}

shoppr_site/shoppr_app/templates/shoppr_app/register.html
{% extends 'shoppr_app/base.html' %}
{% block content %}

{% load crispy_forms_tags %}
{% load socialaccount %}
{% load static %}

	{% if messages %}
		<ul class="messages">
		    {% for message in messages %}
		    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
		    {% endfor %}
		</ul>
	{% endif %}
	<center>
		<div>
			<a href="{% provider_login_url 'google' %}" class="text-dark">
				<img src="{% static 'shoppr_app/img/google_sign_in.png' %}" style="width:14rem; height:auto">
			</a>
		</div>
	</center>

  <div style="width: 100%; height: 15px; border-bottom: 1px solid lightgray; text-align: center">
    <span class="text-muted" style="margin-top:-15% !important; font-size: 11px; background-color: white; padding: 0px 10px;">
      OR
    </span>
  </div>

  <br><br>

    <div class="register-login-section spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 offset-lg-3">
                    <div class="register-form">
                        <h2>Register</h2>
                        <form method="post" action="{% url 'shoppr_app:register' %}">
                        	{% csrf_token %}
                            <div class="group-input" id = "div_id_username">
                                <label for="id_username" class="requiredField">Username *</label>
                                <input type="text" id="id_username" name = "username" maxlength = '150' autofocus required >
                            </div>
                            <div class="group-input" id = "div_id_email">
                                <label for="id_email" class="requiredField">Email address *</label>
                                <input type="email" id="id_email" name = "email" required >
                            </div>

                            <div class="group-input" id="div_id_password1">
                                <label for="id_password1" class="requiredField">Password *</label>
                                <input type="password" id="id_password1" name="password1" required autocomplete='new_password'>
                            </div>
                            <div class="group-input" id="div_id_password2">
                                <label for="id_password2" class="requiredField">Confirm Password *</label>
                                <input type="password" id="id_password2" name="password2" required autocomplete='new_password'>
                            </div>
                            <button type="submit" class="site-btn register-btn">REGISTER</button>
                        </form>
                        <br>
                        <div class="switch-login">
                            <a href="{% url 'shoppr_app:login' %}" class="or-login">Or Login</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

<!-- <form method="post">
    {% csrf_token %}
    {{ register_form|crispy }}
    <button type="submit"  class="btn btn-primary">Register</button>

  </form>
  <br>
  <p class="text-center">Already have an account? <a href="{% url 'shoppr_app:login' %}">Log In</a>.</p> -->



{% endblock %}